name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Check Ubuntu version
        run: cat /etc/lsb-release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-options: network=host

      - name: Build with Maven
        run: mvn -B clean package

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zeljana/intens-praksa:latest

      - name: Deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: 192.168.1.1
          username: zeljanazegarac
          script: |
            docker pull zeljana/intens-praksa:latest
            docker stop praksa-app || true
            docker rm praksa-app || true
            docker run -d -p 8080:8080 --name praksa-app zeljana/intens-praksa:latest
