name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B clean package

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zeljana/intens-praksa:latest

    - name: Deploy Docker image
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.1
        username: zeljanazegarac
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
                  docker pull zeljana/intens-praksa:latest
                  docker stop praksa-app || true
                  docker rm praksa-app || true
                  docker run -d -p 8080:8080 --name praksa-app zeljana/intens-praksa:latest